# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'getColor.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(353, 149)
        Form.setMouseTracking(False)
        Form.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.colorShow = QtWidgets.QLabel(Form)
        self.colorShow.setGeometry(QtCore.QRect(30, 40, 80, 80))
        self.colorShow.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.colorShow.setText("")
        self.colorShow.setObjectName("colorShow")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(140, 70, 181, 21))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cssText = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cssText.setFont(font)
        self.cssText.setObjectName("cssText")
        self.horizontalLayout_2.addWidget(self.cssText)
        self.cssValue = QtWidgets.QLineEdit(self.layoutWidget)
        self.cssValue.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cssValue.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 170, 0);")
        self.cssValue.setObjectName("cssValue")
        self.horizontalLayout_2.addWidget(self.cssValue)
        self.layoutWidget_2 = QtWidgets.QWidget(Form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(140, 100, 181, 21))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.posText = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.posText.setFont(font)
        self.posText.setObjectName("posText")
        self.horizontalLayout_3.addWidget(self.posText)
        self.posValue = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.posValue.setFocusPolicy(QtCore.Qt.NoFocus)
        self.posValue.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 170, 0);")
        self.posValue.setText("")
        self.posValue.setObjectName("posValue")
        self.horizontalLayout_3.addWidget(self.posValue)
        self.colorSelectPanel = QtWidgets.QPushButton(Form)
        self.colorSelectPanel.setGeometry(QtCore.QRect(30, 10, 21, 21))
        self.colorSelectPanel.setText("")
        self.colorSelectPanel.setObjectName("colorSelectPanel")
        self.get_color_btn = QtWidgets.QPushButton(Form)
        self.get_color_btn.setGeometry(QtCore.QRect(239, 10, 81, 20))
        self.get_color_btn.setObjectName("get_color_btn")
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(140, 40, 181, 21))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rgbText = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rgbText.setFont(font)
        self.rgbText.setObjectName("rgbText")
        self.horizontalLayout.addWidget(self.rgbText)
        self.rgbValue = QtWidgets.QLineEdit(self.layoutWidget1)
        self.rgbValue.setFocusPolicy(QtCore.Qt.NoFocus)
        self.rgbValue.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 170, 0);")
        self.rgbValue.setObjectName("rgbValue")
        self.horizontalLayout.addWidget(self.rgbValue)

        self.retranslateUi(Form)
        self.colorSelectPanel.clicked.connect(Form.openColorPanel)
        self.get_color_btn.clicked.connect(Form.changeMouseStyle)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.cssText.setText(_translate("Form", "CSS值： "))
        self.cssValue.setText(_translate("Form", "#00aaff"))
        self.posText.setText(_translate("Form", "坐标值："))
        self.get_color_btn.setText(_translate("Form", "取色(Alt)"))
        self.rgbText.setText(_translate("Form", "RGB值： "))
        self.rgbValue.setText(_translate("Form", "0, 170, 255"))
